config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  resources :claims, only: [:new, :create, :show]

  namespace :admin do
    resources :claims, only: [:index, :edit, :update]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/claim.rb
class Claim < ApplicationRecord
  extend Enumerize

  validates :claim_number, :claimant_name, :email, :accident_date, :status, presence: true

  enumerize :status, in: %I[in_progress evaluation approval rejection], default: :in_progress
end

app/controllers/admin/claims_controller.rb
class Admin::ClaimsController < ApplicationController
  before_action :find_claim, only: [:edit, :update]

  def index
    @claims = Claim.all
  end

  def edit
  end

  def update
    @claim.assign_attributes(claim_params)

    if @claim.save
      flash[:success] = 'Claim has been updated'
      redirect_to admin_claims_path
    else
      flash[:error] = "Claim has not been updated with error: #{@claim.errors.full_messages.to_sentence}"
      render :edit
    end
  end

  private

  def find_claim
    @claim = Claim.find(params[:id])
  end

  def claim_params
    params.require(:claim).permit(:status)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  rescue_from ActiveRecord::RecordNotFound, with: :not_found

  private

  def not_found
    render file: 'public/404.html', status: :not_found, layout: false
  end
end

app/controllers/claims_controller.rb
class ClaimsController < ApplicationController
  before_action :find_claim, only: :show

  def new
    @claim = Claim.new(accident_date: Time.zone.today)
  end

  def create
    @claim = Claim.new(claim_params)

    if ClaimCreator.new(@claim).create
      flash[:success] = 'Claim has been created'
      redirect_to claim_path(@claim)
    else
      flash[:error] = "Claim has not been created with error: #{@claim.errors.full_messages.to_sentence}"
      render :new
    end
  end

  def show
  end

  private

  def find_claim
    @claim = Claim.find(params[:id])
  end

  def claim_params
    params.require(:claim)
          .permit(:claim_number, :claimant_name, :email, :accident_date)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/claims/_claim.html.erb
<tr>
  <td><%= claim.id %></td>
  <td><%= claim.claim_number %></td>
  <td><%= claim.claimant_name %></td>
  <td><%= claim.email %></td>
  <td><%= claim.accident_date %></td>
  <td><%= claim.status_text %></td>
  <td><%= link_to("Edit", edit_admin_claim_path(claim)) %></td>
</tr>

app/views/admin/claims/_form.html.erb
<%= form_for [:admin, @claim] do |f| %>
  <div>
    <label>Claim number: </label>
    <%= @claim.claim_number %>
  </div>

  <div>
    <label>Claimant name: </label>
    <%= @claim.claimant_name %>
  </div>

  <div>
    <label>Email: </label>
    <%= @claim.email %>
  </div>

  <div>
    <label>Accident date: </label>
    <%= @claim.accident_date %>
  </div>

  <div>
    <%= f.label :status %>
    <%= f.select(:status, Claim.status.options) %>
  </div>

  <div>
    <%= f.submit 'Submit' %>
  </div>
<% end %>

app/views/admin/claims/edit.html.erb
<h3>Edit claim</h3>

<%= render 'shared/flash_messages' %>

<%= render 'form' %>

app/views/admin/claims/index.html.erb
<h3>Claims</h3>

<%= render 'shared/flash_messages' %>

<table>
  <thead>
    <th>ID</th>
    <th>Claim number</th>
    <th>Claimant name</th>
    <th>Email</th>
    <th>Accident date</th>
    <th>Status</th>
    <th></th>
  </thead>
  <tbody>
    <%= render @claims %>
  </tbody>
</table>

app/views/claims/_form.html.erb
<%= form_for @claim do |f| %>
  <div>
    <%= f.label :claim_number %>
    <%= f.text_field :claim_number, required: true %>
  </div>

  <div>
    <%= f.label :claimant_name %>
    <%= f.text_field :claimant_name, required: true %>
  </div>

  <div>
    <%= f.label :email %>
    <%= f.email_field :email, required: true %>
  </div>

  <div>
    <%= f.label :accident_date %>
    <%= f.date_field :accident_date, required: true %>
  </div>

  <div>
    <%= f.submit 'Submit' %>
  </div>
<% end %>

app/views/claims/new.html.erb
<h3>New claim</h3>
<%= render 'form' %>

app/views/claims/show.html.erb
<%= link_to('New claim', new_claim_path) %>

<%= render 'shared/flash_messages' %>

<div>
  <label>Claim number: </label>
  <%= @claim.claim_number %>
</div>

<div>
  <label>Claimant name: </label>
  <%= @claim.claimant_name %>
</div>

<div>
  <label>Email: </label>
  <%= @claim.email %>
</div>

<div>
  <label>Accident date: </label>
  <%= @claim.accident_date %>
</div>

app/views/home/index.html.erb
<%= link_to("New claim", new_claim_path) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ClaimTracking</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_flash_messages.html.erb
<% if flash[:success] %>
  <p><%= flash[:success] %></p>
<% end %>

<% if flash[:error] %>
  <p><%= flash[:error] %></p>
<% end %>